version: '3.5'
services:
  mysql6:
    image: mysql:8.0.26
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: on-failure
    container_name: mysql_container
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "local_db"
      MYSQL_USER: "local_user"
      MYSQL_PASSWORD: "P@ssw0rd!"

  adminer:
    image: adminer:latest
    restart: on-failure
    ports:
      - 8081:8080
volumes:
  db_data: {}
